name: auto_excel
channels:
- defaults
dependencies:
- python==3.9.*
- pip
- autopep8
- jupyterlab
- ipywidgets

- pip:
  - matplotlib
  - seaborn
  - pandas
  - chromadb
  - selenium
  - openpyxl
  - beautifulsoup4
  - llama-index
  - llama-index-vector-stores-chroma
  - llama-index-llms-anthropic
  - llama-index-experimental
  - openai
  - tabulate
  - requests
  - pytest
  - python-dotenv
  - -e .

